export const shopActionTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
  
  // Redux Thunk Action Types
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
}